Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -3,8 +3,8 @@ name: Development workflow
 on: 
   workflow_dispatch:
     inputs:
-      username:
-        description: 'Enter your name'
+      ProjectVersion:
+        description: 'Enter the version Number to deploy'
         required: true
       environment:
         description: 'Select environment'
@@ -27,5 +27,15 @@ jobs:
         run: |
           project_name=$(jq -r '.name' project.json)
           main_file=$(jq -r '.main' project.json)
+          project_Version = $(jq -r '.main' project.json)
           echo "Project Name: $project_name"
+          echo "Project Version: $project_Version"
           echo "Main File: $main_file"
+          
+      - name: Validate environment variable
+        run: |
+          if [[ "$project_Version" != "$ProjectVersion"]]; then
+            echo "Invalid ProjectVersion value: $ProjectVersion"
+            exit 1
+          fi
+           echo "Validation successful!" 
